

DROP TABLE CHARACTERS; 
CREATE TABLE CHARACTERS 
(
ET_ID int PRIMARY KEY NOT NULL,
NAME VARCHAR(225),
LEVEL INT,
JOB_ID INT NOT NULL,
HEALTH INT,
INVENTORY_ID INT NOT NULL,
EXP INT,
EXP_FOR_LEVEL INT
);


DROP TABLE ABILITIES;
CREATE TABLE ABILITIES
(
ABILITY_ID INT PRIMARY KEY,
ABILITY_NAME VARCHAR(335) NOT NULL,
ABILITY_DESCRIPTOR VARCHAR(225),
ABILITY_TARGET  VARCHAR(225) NOT NULL,
ABILITY_DAMAGE INT,
HIT_CHANCE INT,
COOL_DOWN INT
);

INSERT INTO ABILITIES VALUES(1, 'REND', 'SLASH WITH YOUR WEAPON', 'ENEMY', 5, 90, 0);
INSERT INTO ABILITIES VALUES(2, 'CHARGE', 'CHARGE YOUR ENEMY MAKING THEM SKIP THEIR TURN', 'ENEMY', NULL, 100, 4);
INSERT INTO ABILITIES VALUES(3, 'BOLSTER', 'BOLSTER YOUR ARMOR FOR THE REST OF THIS FIGHT(STACKABLE)', 'ARMOR', 5, 100, 3);
INSERT INTO ABILITIES VALUES(4, 'FIREBALL', 'SHOOT A BALL OF FIRE AT YOUR ENEMY', 'ENEMY', 5, 90, 0);
INSERT INTO ABILITIES VALUES(5, 'ICY TOUCH', 'DAMAGE AN ENEMY INCREASING THE TURN COUNTER FOR THE NEXT SPELL THEY USE', 'ENEMY', 2, 50, 4);
INSERT INTO ABILITIES VALUES(6, 'DISPERSION', 'DISPERSE YOUR FORM CAUSING THE NEXT TWO ENEMY ATTACKS TO MISS', 'SELF', NULL, 100, 6);
INSERT INTO ABILITIES VALUES(7, 'SMITE', 'CALL THE POWER OF THE LIGHT ON YOUR ENEMY', 'ENEMY', 5, 90, 0);
INSERT INTO ABILITIES VALUES(8, 'HEAL', 'HEAL YOURSELF', 'SELF', 10, 100, 3);
INSERT INTO ABILITIES VALUES(9, 'ABSORB', 'CREATE AN ABSORB SHEILD GIVING YOU ARMOR FOR THE NEXT TWO TURNS', 'ARMOR', 5, 100, 2);
INSERT INTO ABILITIES VALUES(10, 'STAB', 'STAB WITH YOUR WEAPON', 'ENEMY', 5, 90, 0);
INSERT INTO ABILITIES VALUES(11, 'POISON VIAL', 'THROW A POISION WEAPON AT YOUR ENEMY(ALWAYS CRITS)', 'ENEMY', 5, 90, 0);
INSERT INTO ABILITIES VALUES(12, 'EVASION', 'YOUR OPPENENT MISSES THEIR NEXT ATTACK', 'SELF', NULL, 100, 0);

SELECT * FROM CHARACTERS;
SELECT * FROM ABILITIES;